name: Go

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: kerberos/base:0a50dc9
      
    strategy:
      matrix:
        go-version: ['1.17', '1.18', '1.19', '1.20', '1.21']

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Get dependencies
      run: cd machinery && go mod download
    - name: Build
      run: cd machinery && go build -v ./...
    - name: Vet
      run: cd machinery && go vet -v ./...
    - name: Test
      run: cd machinery && go test -v ./...
